### ISSUE TITLE
Release 1.1.0-rc.1

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tutorials#209]
### atac

- [x] PeakVI #165 
- [x] PoissonVI #179 
- [x] scbasset_batch #166 
- [ ] scbasset https://github.com/scverse/scvi-tutorials/actions/runs/7133507513

### dev

- [x] data_tutorial #180 
- [x] model_user_guide #167 
- [x] module_user_guide #168 

### hub

- [x] minification #169 
- [ ] scvi_hub_intro_and_download #174 
- [x] scvi_hub_upload_and_large_files #170 

### multimodal

- [x] cite_scrna_integration_w_totalVI #171 
- [x] MultVI_tutorial #172 
- [x] totalVI_reference_mapping #175 
- [x] totalVI #176 

### quick_start

- [x] api_overview #177 
- [x] data_loading #178 

### scrna

- [x] amortized_lda #181 
- [x] AutoZI_tutorial #182 
- [x] cellassign_tutorial #190 
- [x] contrastiveVI_tutorial #204 
- [x] harmonization #186 
- [x] linear_decoder #183 
- [x] query_hlca_knn #184 
- [ ] scarches_scvi_tools https://github.com/scverse/scvi-tutorials/actions/runs/7133671731/job/19426842721
- [x] scVI_DE_worm #185 
- [x] seed_labeling #187 
- [x] tabula_muris #189 

### spatial

- [ ] cell2location_lymph_node_spatial_tutorial https://github.com/scverse/scvi-tutorials/actions/runs/7122671576/job/19394075468
- [ ] DestVI_tutorial https://github.com/scverse/scvi-tutorials/actions/runs/7122672392/job/19394077690
- [x] gimvi_tutorial #199 
- [x] stereoscope_heart_LV_tutorial #197 
- [ ] tangram_scvi_tools https://github.com/scverse/scvi-tutorials/actions/runs/7122675417/job/19394086030

### tuning

- [x] autotune_new_model #194 
- [x] autotune_scvi #201

**Comment by martinkim0** [comment]
Remaining tutorials will be fixed and rerun for either 1.0.0-rc.2 or 1.1.0
