### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tutorials#210]
### atac

- [x] PeakVI #236
- [x] PoissonVI #235
- [ ] scbasset_batch https://github.com/scverse/scvi-tutorials/actions/runs/7876877984/job/21491824752#step:5:186
- [ ] scbasset

### dev

- [x] data_tutorial #237
- [x] model_user_guide #238
- [x] module_user_guide #239

### hub

- [x] minification #242
- [x] scvi_hub_intro_and_download #240
- [x] scvi_hub_upload_and_large_files #241

### multimodal

- [x] cite_scrna_integration_w_totalVI #243
- [x] MultVI_tutorial #244
- [x] totalVI_reference_mapping #248
- [x] totalVI #245

### quick_start

- [x] api_overview #246 
- [x] data_loading #247

### scrna

- [x] amortized_lda #251
- [x] AutoZI_tutorial #249
- [x] cellassign_tutorial #250
- [x] contrastiveVI_tutorial #255
- [x] harmonization #252
- [x] linear_decoder #253
- [x] query_hlca_knn #254
- [ ] scarches_scvi_tools https://github.com/scverse/scvi-tutorials/actions/runs/7875696105/job/21488129760#step:5:391
- [x] scanvi_fix #256
- [x] scVI_DE_worm #258
- [x] seed_labeling #257
- [x] tabula_muris #260

### spatial

- [ ] cell2location_lymph_node_spatial_tutorial https://github.com/scverse/scvi-tutorials/actions/runs/7875700829/job/21488144818#step:5:142
- [ ] DestVI_tutorial https://github.com/scverse/scvi-tutorials/actions/runs/7875702231/job/21488150334#step:5:123
- [x] gimvi_tutorial #259
- [x] stereoscope_heart_LV_tutorial #261
- [ ] tangram_scvi_tools https://github.com/scverse/scvi-tutorials/actions/runs/7875705031/job/21488159741#step:5:122

### tuning

- [x] autotune_new_model #262
- [x] autotune_scvi #265
